---
channel: stable
addons:
  portainer:
    repository: portainer/portainer
    target: portainer
    image: registry.hub.docker.com/library/portainer/portainer
  hello-world:
    repository: hello-world
    target: hello-world
    image: hello-world
